[msd3 - 02_first_program] Drugi rozdzial: drobne poprawki
MarcinMoskala/kotlin_essentials_book_pl pull request #22
Opened 2023-04-24 19:39 UTC by msd3

Drugi rozdzial: drobne poprawki: odmiana Kotlin, Java i bytecode; Małe zmiany szyku zdań oraz poprawa stylistyki.

2023-04-24 19:42 UTC, timberwolve commented
Wystąpiły konflikty. Do ogarnięcia! :-)

2023-04-25 04:48 UTC, msd3 commented
Oj, nieuwaga z mojej strony!

2023-04-25 04:54 UTC, MarcinMoskala requested changes

2023-04-25 04:54 UTC, MarcinMoskala commented on manuscript/02_first_program.md
> +Niewiele potrzeba, prawda? Nie potrzebujemy klas (jak w Javie), żadnych obiektów (jak `console` w JavaScripcie) ani warunków (jak w Pythonie). Potrzebujemy funkcji `main` oraz wywołania funkcji `prin
Stanowczo lepiej :)

2023-04-25 04:54 UTC, MarcinMoskala commented on manuscript/02_first_program.md
> +Chociaż wszystkie te formy są poprawne, skupmy się na prostym `main`, gdyż będzie on najbardziej użyteczny. Użyję go niemal w każdym przykładzie w tej książce i zazwyczaj będą w pełni wykonywalne, je
Tutaj akurat zmniejszona jest czytelność, bo pierwsza szęść zdania "go" odnosi się do `main`, a druga "będę" do przykładów. 
Zmieniłbym na ". Te przykłady są zazwyczaj będą w pełni"

2023-04-25 04:54 UTC, MarcinMoskala commented on manuscript/02_first_program.md
> +To świetne miejsce dla każdego, kto lubi czytać bytecode JVM. Ponieważ nie wszyscy są jak Jake Wharton, w związku z tym większość z nas może uznać przycisk "Decompile" za przydatny. To, co robi, jest
Stanowczo, dodałbym do Readme tłumaczenie:
**bytecode** - **bytecode**

2023-05-02 09:01 UTC, MarcinMoskala commented on manuscript/02_first_program.md
> +To świetne miejsce dla każdego, kto lubi czytać bytecode JVM. Ponieważ nie wszyscy są jak Jake Wharton, w związku z tym większość z nas może uznać przycisk "Decompile" za przydatny. To, co robi, jest
Dodałem

2023-05-02 09:06 UTC, MarcinMoskala approved these changes

2023-05-02 09:09 UTC, merged