Timberwolve 000 intro.md
MarcinMoskala/kotlin_essentials_book_pl pull request #39
Opened 2023-05-18 17:34 UTC by timberwolve

2023-05-22 19:31 UTC, msd3 requested changes
Wymagadana niewielka poprawka - w słowie Android (jest: ANdroid)

2023-05-22 19:31 UTC, msd3 commented on manuscript/000_intro.md
> +Kotlin to niesamowity język wieloplatformowy, o czytelnej składni, bezpiecznym systemie typów oraz ogromnym wsparciu ze strony narzędzi programistycznych. Nic dziwnego, że Google wybrał go na oficjal
W slowie Android wkradła się litera 'N'

2023-05-23 06:42 UTC, MarcinMoskala commented on manuscript/000_intro.md
> +Ta książka jest dedykowana programistom. Zakładam, że wszyscy programiści wiedzą, czym są funkcje lub metody, instrukcje warunkowe if czy ciągi znaków. Niemniej jednak staram się wyjaśnić (przynajmni
metody to również funkcje

2023-05-23 07:21 UTC, MarcinMoskala commented
Masz bardzo miły styl pisania, kilka rzeczy jednak zmieniłem by zachować oryginalny sens.

2023-05-23 07:21 UTC, merged