[msd3 - 11_data_classes] Jedenasty rozdział: Korekta wyjaśnienia dotyczącego funkcji hashCode. Poprawki stylistyczne i inne.
MarcinMoskala/kotlin_essentials_book_pl pull request #48
Opened 2023-05-28 17:40 UTC by msd3

W opisie funkcji hashCode pojawiło się wyjaśnienie, że jest mocno oparta na adresie obiektu w pamięci. JVM domyślnie zwraca liczbę oznaczającą tzw Identity Hash Code, co przetłumaczylem jako hash kod tożsamości (nie wiem, czy zgrabnie i poprawnie :) Szczególnie w przypadku maszyn i systemów 64-bitowych w celu dokladnego określenia adresu potrzebowalibyśmy wartości Long.

https://github.com/JetBrains/kotlin/blob/924c28507067cbfbf78a6509ea89eabe496e34ca/kotlin-native/runtime/src/main/kotlin/kotlin/Any.kt#L39

https://shipilev.net/jvm/anatomy-quarks/26-identity-hash-code/

2023-05-29 07:35 UTC, MarcinMoskala requested changes

2023-05-29 07:35 UTC, MarcinMoskala commented on manuscript/11_data_classes.md
> +* `hashCode` - używana przez kolekcje, które korzystają z kodów hash trzymanych w nich obiektów,
Myślę, że "algorytm hash table" jest jednak bardziej zrosumiały i wyszukiwalny

2023-05-29 07:35 UTC, MarcinMoskala commented on manuscript/11_data_classes.md
> +Domyślne implementacje `equals`, `hashCode` i `toString` są oparte na tak zwanym kodzie hash tożsamości (`System.identityHashCode()`). Metoda `equals` zwraca `true` tylko wtedy, gdy dla obu obiektów
Pierwszo słyszę o "kodzie hash tożsamości" i nie wydaje mi się to upraszczać tematu, pozostałbym przy "mocno oparte na adresie obiektu w pamięci."

2023-05-29 07:35 UTC, MarcinMoskala commented on manuscript/11_data_classes.md
> +Destrukturyzacja pojedynczej wartości jest bardzo myląca. Zwłaszcza w funkcji lambda, gdzie nawiasy wokół argumentów w wyrażeniach lambda są, w zależności od gramatyki języka programowania, opcjonaln
Wprowadzenie pojęcia gramatyki języka jest niepotrzebne a utrudnia temat

2023-05-29 07:35 UTC, MarcinMoskala commented on manuscript/11_data_classes.md
> +   println(d1) // Dog(name = Cookie)
O ile pamiętam, nie ma spacji w wygenerowanym stringu

2023-05-29 07:35 UTC, MarcinMoskala commented on manuscript/11_data_classes.md
> +To prawie nic nie kosztuje i znacznie poprawia czytelność i czystość kodu:
"czytelność i czystość kodu" więcej przekazywało

2023-05-29 07:37 UTC, MarcinMoskala commented
@msd3 Miło, że wchodzisz głębiej w tematy i posiadasz dużą wiedzę, jak widać, w tym przypadku przewyższającą moją, niemniej wydaje mi się że za dużo pojawiło się tu niepotrzebnych dla czytelnika szczegółów i wolałbym byśmy w ich przypadku zrobili krok w tył.

2023-05-30 14:39 UTC, msd3 commented on manuscript/11_data_classes.md
> +* `hashCode` - używana przez kolekcje, które korzystają z kodów hash trzymanych w nich obiektów,
OK, zmienię

2023-05-30 14:53 UTC, msd3 commented on manuscript/11_data_classes.md
> +Destrukturyzacja pojedynczej wartości jest bardzo myląca. Zwłaszcza w funkcji lambda, gdzie nawiasy wokół argumentów w wyrażeniach lambda są, w zależności od gramatyki języka programowania, opcjonaln
OK, zmienię

2023-06-05 04:44 UTC, merged

2023-06-05 04:44 UTC, MarcinMoskala commented
I super :)